# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arch/dev/clocker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arch/dev/clocker/CarbonEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arch/dev/clocker/CarbonEngine/CMakeFiles /home/arch/dev/clocker/CarbonEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arch/dev/clocker/CarbonEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clocker

# Build rule for target.
clocker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clocker
.PHONY : clocker

# fast build rule for target.
clocker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clocker.dir/build.make CMakeFiles/clocker.dir/build
.PHONY : clocker/fast

#=============================================================================
# Target rules for targets named Nova

# Build rule for target.
Nova: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nova
.PHONY : Nova

# fast build rule for target.
Nova/fast:
	$(MAKE) $(MAKESILENT) -f CarbonEngine/CMakeFiles/Nova.dir/build.make CarbonEngine/CMakeFiles/Nova.dir/build
.PHONY : Nova/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) $(MAKESILENT) -f CarbonEngine/CMakeFiles/core.dir/build.make CarbonEngine/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named shadermanager

# Build rule for target.
shadermanager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shadermanager
.PHONY : shadermanager

# fast build rule for target.
shadermanager/fast:
	$(MAKE) $(MAKESILENT) -f CarbonEngine/CMakeFiles/shadermanager.dir/build.make CarbonEngine/CMakeFiles/shadermanager.dir/build
.PHONY : shadermanager/fast

#=============================================================================
# Target rules for targets named fontc

# Build rule for target.
fontc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fontc
.PHONY : fontc

# fast build rule for target.
fontc/fast:
	$(MAKE) $(MAKESILENT) -f CarbonEngine/CMakeFiles/fontc.dir/build.make CarbonEngine/CMakeFiles/fontc.dir/build
.PHONY : fontc/fast

#=============================================================================
# Target rules for targets named box2d

# Build rule for target.
box2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 box2d
.PHONY : box2d

# fast build rule for target.
box2d/fast:
	$(MAKE) $(MAKESILENT) -f CarbonEngine/external/box2d/src/CMakeFiles/box2d.dir/build.make CarbonEngine/external/box2d/src/CMakeFiles/box2d.dir/build
.PHONY : box2d/fast

#=============================================================================
# Target rules for targets named volk

# Build rule for target.
volk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 volk
.PHONY : volk

# fast build rule for target.
volk/fast:
	$(MAKE) $(MAKESILENT) -f CarbonEngine/external/volk/CMakeFiles/volk.dir/build.make CarbonEngine/external/volk/CMakeFiles/volk.dir/build
.PHONY : volk/fast

# target to build an object file
cmake_pch.h.gch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clocker.dir/build.make CMakeFiles/clocker.dir/cmake_pch.h.gch
.PHONY : cmake_pch.h.gch

# target to preprocess a source file
cmake_pch.h.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clocker.dir/build.make CMakeFiles/clocker.dir/cmake_pch.h.i
.PHONY : cmake_pch.h.i

# target to generate assembly for a file
cmake_pch.h.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clocker.dir/build.make CMakeFiles/clocker.dir/cmake_pch.h.s
.PHONY : cmake_pch.h.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clocker.dir/build.make CMakeFiles/clocker.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clocker.dir/build.make CMakeFiles/clocker.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clocker.dir/build.make CMakeFiles/clocker.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Nova"
	@echo "... box2d"
	@echo "... clocker"
	@echo "... core"
	@echo "... fontc"
	@echo "... shadermanager"
	@echo "... volk"
	@echo "... cmake_pch.h.gch"
	@echo "... cmake_pch.h.i"
	@echo "... cmake_pch.h.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

